### PR TITLE
Add useful methods on the Solution struct

### PR DESCRIPTION
**Pull request by lovasoa**
Unfortunately, it looks like there is no more getRowPrice in the C API: https://github.com/coin-or/Cbc/issues/370

### CODE REVIEW

**Comment by lovasoa** [comment]
Hmm, it looks like Cbc's C API is really a moving target. The old libcbc is missing `Cbc_getReducedCost`.

**Comment by TeXitoi** [comment]
reduce cost and dual variable doesn't have so much meaning in MILP, only in continuous LP.

**Comment by lovasoa** [comment]
Yes, they are very useful in resource allocation problems, for instance.

**Comment by TeXitoi** [comment]
The thibg is that cbc is designed for MILP. Of you need only a LP, you should use CPL (which is used by default by CBC as a tool) that has a much better interface to manage the LP. That's why duals and redux costs are not well supported in the cbc c api.

**Comment by lovasoa** [comment]
Cbc does expose the needed functions in its C++ API, it's just that the C API is a kind of second-class citizen. I do agree that these functions are less useful for integer variables, but there is considerable value in not having to switch libraries and APIs when you add an integer variable to an existing continuous problem. I don't think there would be any value for maintaining a separate Clp binding in rust with a different API.

**Comment by TeXitoi** [comment]
Sure. But what do we do here? As is, it doesn't compile with CBC 2.9.

**Comment by lovasoa** [comment]
Maybe we can put these new methods behind a new cbc-310 feature flag?

**Comment by TeXitoi** [comment]
I'm not fan of feature flags, but I don't see any other solution.

**Comment by lovasoa** [comment]
Ok. I also added functions to test the installed libcbc version

**Comment by lovasoa** [comment]
@TeXitoi can this be merged ?

**Comment by TeXitoi** [comment]
Sorry for the delay

**Comment by TeXitoi** [comment]
v0.1.5 published

**Comment by lovasoa** [comment]
Thanks !

**Pull request merged**
