### PR TITLE
Add a test for #9

### PR DESCRIPTION
**Pull request by lovasoa**
This adds a test for #9. You should see the reproduction on the CI run.

### CODE REVIEW

**Comment by TeXitoi** [comment]
I have similar errors without this added test.

**Comment by lovasoa** [comment]
What do you mean ? Do you have errors running `cargo test` on master ? I don't.

**Comment by TeXitoi** [comment]
I do

**Comment by TeXitoi** [comment]
Also, I don't have the same result with the multithread test

**Comment by TeXitoi** [comment]
like 1/10 it fails

**Comment by lovasoa** [comment]
Running 

```
 S=0; F=0; for i in {1..100}; do cargo test; if [ $? == 0 ]; then let S+=1; else let F+=1; fi; done; echo "Successes: $S"; echo "Failures: $F"
```

I get

```
Successes: 100
Failures: 0
```

Both on Linux and MacOS

**Comment by TeXitoi** [comment]
I don't have the same lib as you I suppose, I have the debian stable one.

```
i=0; while cargo test; do i=$((i+1)); done; echo $i
```

gives between 0 and 11 depending on the case.

**Comment by lovasoa** [comment]
I have the latest one in ubuntu: 2.10.5. 
Debian stable has 2.9.9 :  https://packages.debian.org/buster/coinor-libcbc-dev
It probably has bugs that have been fixed in more recent versions.

**Comment by lovasoa** [comment]
If the bug is a memory corruption bug, you may get debian to issue a security update on stable.

**Comment by TeXitoi** [comment]
I clearly need the lock for the `raw::Model::new`

**Comment by lovasoa** [comment]
Ok, let's add it then

**Comment by TeXitoi** [comment]
I also don't have the same results on the tests, but I don't see what we can do for that

**Comment by TeXitoi** [comment]
With the lock on new, this test pass here.

**Comment by TeXitoi** [comment]
```diff
+                        // Solve an empty problem
+                        let mut m = Model::new();
+                        m.load_problem(1, 0, &[0, 0], &[], &[], None, None, None, None, None)
;
+                        m.solve();
+                        assert_eq!(Status::Finished, m.status());
+                        assert_eq!(SecondaryStatus::HasSolution, m.secondary_status());
+                        assert!((m.col_solution()[0]).abs() < 1e-6);
```

**Comment by TeXitoi** [comment]
I'll open a PR within a few minutes for my problems.

**Comment by TeXitoi** [comment]
https://github.com/KardinalAI/coin_cbc/pull/13

**Comment by TeXitoi** [comment]
So, as this test pass on my coin version, can we say that's a coin bug and close this?

**Comment by lovasoa** [comment]
Yes, this is a bug in cbc. I reported it as https://github.com/coin-or/Cbc/issues/367

**Pull request closed without merging**
